apiVersion: ingka.com/v1alpha1
kind: ComponentTemplate
metadata:
  name: fli-demo-template
  description: FLI Demo Template
  title: FLI Demo Template
  tags:
    - java
    - api
    - microservice
    - backend
spec:
  owner: ilo-fli
  type: service # library, website, documentation, x
  config:
    componentName: $(userInput.componentName)
    description: $(userInput.description)
    owner: $(userInput.owner)
  template: fli-demo-template
  user_input: |
    {
      "title": "Template variables",
      "description": "These variables are required for the template",
      "type": "object",
      "properties": {
        "componentName": {
          "title": "Component Name",
          "description": "Name of Component",
          "type": "string"
        },
        "description": {
          "title": "Description",
          "description": "Component Description",
          "type": "string"
        },
        "owner": {
          "title": "Owning Team",
          "description": "Owner - INGKA Team",
          "type": "string"
        }
      },
      "required": ["componentName", "description", "owner"]
    }
  dependencies:
    - type: github-repository
      spec: {}
