apiVersion: ingka.com/v1alpha1
kind: ComponentTemplate
metadata:
  name: ilo-fli-allen-create-comp-demo
  description: FLI Demo Template
  title: FLI Demo Template
  tags:
    - python
    - example
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/ingka-group-digital/ilo-fli-allen-create-comp-demo
spec:
  owner: ilo-fli
  type: service # library, website, documentation, x
  config:
    teamSlug: $(dep.github-repository.team_slug)
    repositoryName: $(dep.github-repository.name)
    componentName: $(userInput.componentName)
    description: $(userInput.description)
    ownerTeam: $(userInput.ownerTeam)
    language: $(userInput.language)
    systemAbbreviation: $(userInput.systemAbbreviation)
  template: ilo-fli-allen-create-comp-demo
  user_input: |
    {
      "title": "Template variables",
      "description": "These variables are required for the template",
      "type": "object",
      "properties": {
        "componentName": {
          "title": "Component Name",
          "description": "Name of Component",
          "type": "string"
        },
        "description": {
          "title": "Description",
          "description": "Component Description",
          "type": "string"
        },
        "ownerTeam": {
          "title": "Owning Team",
          "description": "Owner - INGKA Team",
          "ui:field": "OwnerTeamPicker",
          "default": "ilo-fli"
        },
        "systemAbbreviation":{
          "type":"string",
          "title":"System Abbreviation",
          "description":"The System abbreviation as defined in SMC (System Master Catalog)",
          "ui:field": "SystemPicker",
          "default": "FLI"
        },
        "language":{
          "type":"string",
          "title":"JVM Language",
          "enum":[
             "kotlin",
             "java",
             "python"
          ],
          "default":"python"
          }
      },
      "required": ["componentName", "description", "ownerTeam","systemAbbreviation","language"]
    }
  dependencies:
    - type: github-repository
      spec: {}
